### ISSUE TITLE
UglifyJsPlugin disables scroll

### ISSUE THREAD

**Issue by vetterh1** [cmswalker/fullpage-react#35]
Hi @cmswalker,

Thanks for this nice & useful component!
However, I've some trouble with the UglifyJsPlugin as it seems to break something.

Very easy to replicate by adding these 2 lines in webpack.config.js of your code:
- at the beginning: const webpack = require('webpack');
- in the plugins array, add this:  , new webpack.optimize.UglifyJsPlugin()

The sample will launch but:
- scrolling does not work
- Next / Prev buttons are KO too.

Did I do something wrong?

Thanks :)
Laurent

**Comment by glennflanagan** [comment]
@vetterh1 Did you ever figure this one out? I'm noticing issues with my minified code too.

**Comment by cmswalker** [comment]
@vetterh1 @glennflanagan Sorry this has taken so long.

Turns out, it's the mangling that is breaking. There are various (poorly written) parts within this module that reference the actual TYPE of component being passed around. Unfortunately, when mangled is enabled, this will break fullpage-react.  

You can test it by cloning this repo and running the following

`npm install uglifyjs-webpack-plugin --save-dev`

This webpack config should work for you.
```
const path = require('path');
const HtmlwebpackPlugin = require('html-webpack-plugin');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  entry: {
    index: path.join(__dirname, '/examples/index.js')
  },
  output: {
    filename: '[name].js',
    path: path.join(__dirname, '/static/'),
    publicPath: '/',
    chunkFilename: '[id].chunk.js'
  },
  devServer: {
    inline: true,
    port: 3333
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'react']
        }
      },
      { test: /\.css$/, loader: 'style-loader!css-loader'},
      { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' }
    ]
  },
  plugins: [
    new HtmlwebpackPlugin({
      title: 'Fullpage React'
    }),
    new UglifyJSPlugin({
      mangle: false
    })
  ]
};

```

`npm start`
