### ISSUE TITLE
is it possible to import vertical slides into horizontal slides

### ISSUE THREAD

**Issue by stayge-terry** [cmswalker/fullpage-react#50]
For example
```
<FullPage>
<Horizontal Slider1><Horizontal Slider2><Horizontal Slider3>
</FullPage>
```

and then

vertical Slides compose Horizontal Slider2 like this.

```
<Horizontal Slider2>
<Slide>
<Slide>
<Slide>
</Horizontal Slider2>
```

In your example you imported Horizontal Slider in vertical Slides,
so I thought the opposite would be possible, but I'm having problem in doing this.
Is it possible?

**Comment by cmswalker** [comment]
The reason it isn't possible is because you have to have at least one Vertical slide. So if you need a horizontal slider made up of slides that only slide left to right, the example should suffice.  Horizontal Sliders are Slides themselves in that they are 100% width and 100% height and scroll vertically. It's their composite components that slide left to right.

Are you saying you need vertical slides inside of a horizontal? If that were the case, you'd just place a `<Slide/>` Below the Horizontal itself 

So summary: it shouldn't be a child of horizontal slider, horizontal sliders should only contain horizontal slides

Also in your example, you aren't passing them as props.

```
const slides = [<Slide>, <Slide>, <Slide>];
<HorizontalSlider slides={slides} />
etc
```

Make sense?
