### ISSUE TITLE
Can't get ref in componentDidMount

### ISSUE THREAD

**Issue by LikedBlack** [cmswalker/fullpage-react#99]
`fullPageOptions.slides = [
  <Silde><CustomComponent ref="test"></CustomComponent></Slide>
]`

...

`componentDidMount() {
    console.log(this.refs.test)
  }`

It's output an 'undefined', how can I get this ref?

**Comment by cmswalker** [comment]
My guess is you're not grabbing the ref in the `CustomComponent` class as a prop and passing it within the render function to a `div` `input` etc.

This has nothing to do w/ this library, it's just the implementation of refs in general. Also, if you're passing refs as props, use another name instead of `ref`


https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

```jsx
class MyComp extends React.Component {
      componentDidMount() {
        const { refs } = this;
        console.log({ refs });
      }

      render() {
        return <div ref={this.props.refName}>MyComp</div>;
      }
    }
```

```jsx
<MyComp refName="test"/>
```
